# 配置 WEB 部署
server:
  port: 8083
  servlet:
    context-path: /

# 应用程序名称
spring:
  application:
    name: Unit Testing

# 四大数据源
  datasource:
    url: jdbc:mysql://175.24.128.112:3306/exam
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver